# Generated by Django 2.1 on 2018-08-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=250)),
                ('image', models.URLField()),
            ],
        ),
    ]
